# Generated by Django 6.0 on 2026-04-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctiveaction',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-date_reported'], 'verbose_name': 'Incident', 'verbose_name_plural': 'Incidents'},
        ),
    ]
